matrix:
- name: Markdown
  expect_match: false
  apsell:
    mode: en
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      comments: false
      ignores:
      - code
      markdown_extensions:
      - markdown.extensions.extra:
  sources:
  - '**/*.md'
  - '**/*.MD'
  - '**/*.mdx'
  - '**/*.MDX'
  - '**/*.markdown'
  - '**/*.MARKDOWN'